import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/component/Layout/Header/Navbar/Navbar";
import 'bootstrap/dist/css/bootstrap.min.css';
import HomeFooter from "@/component/Layout/Footer/HomeFooter";


const geistSans = localFont({
  src: "./fonts/Poppins-Medium.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Welcome to metamotion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased containermain`}
      >
        <Navbar/>
        {children}
        <HomeFooter/>
      </body>
    </html>
  );
}
